name: http-tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: Build

    strategy:
      matrix:
        runs-on: [ubuntu-latest, macOS-latest, windows-latest]
        node-version: [12.x]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: npm install
        run: npm install

      - name: Compile
        run: npm run build

      - name: npm test
        run: npm test

      - name: Format
        shell: bash
        run: npm run format-check
        if: matrix.runs-on == 'ubuntu-latest'

      - name: audit security
        continue-on-error: true
        run: npm audit --audit-level=moderate
        if: matrix.runs-on == 'ubuntu-latest'
